config/routes.rb
Rails.application.routes.draw do
  get 'alarm/index'

  get 'alarm/create'

  resources :alarms do
    member do
      put :upvote, to:'alarm#upvote'
    end
  end
  root 'alarm#index'
end

app/models/alarm.rb
class Alarm < ApplicationRecord
  validates :name, :uniqueness => true

  before_save :nameValid

  acts_as_votable

  def nameValid
    name.upcase!
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/voter_session.rb
class VoterSession < ApplicationRecord
  acts_as_voter
end

app/controllers/alarm_controller.rb
require "uri"
require "net/http"
class AlarmController < ApplicationController
  def index
    @alarms = Alarm.order('created_at DESC')
  end

  def create
    @alarm = Alarm.new(alarm_params)

    if @alarm.save
      x = Net::HTTP.post_form(URI.parse('https://bellbird.joinhandshake-internal.com/push'), {alarm_id: @alarm.id})
      redirect_to alarm_index_path
    else
      error_response(@alarm)
    end
  end

  def upvote
    @session = VoterSession.find_by(session_id: request.session_options[:id])
    if @session == nil
      @session = VoterSession.create(session_id: request.session_options[:id])
    end
    @alarm = Alarm.find(params[:id])
    @alarm.upvote_by @session
    redirect_to alarm_index_path
  end

  private
    def alarm_params
      params.permit(:name)
    end

end

app/controllers/alarms/votes_controller.rb
class Alarms::VotesController < ApplicationController

  def create
      @alarm.votes.where(user_id: current_user.id).
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def error_response(object, message = nil, status = nil)
    render json: Error.new(object, message), serializer: ErrorSerializer, status: status || 400
  end

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end
end

app/helpers/alarm_helper.rb
module AlarmHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_controller_helper.rb
module LikesControllerHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/alarm/index.html.erb
<div class = "page-header" style="margin-left:50px"><h1>Bellbird</h1></div>
<div class="container">
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#Modal">
    Create New Alarm
  </button>
    <h3>Alarms</h3>
      <% @alarms.each do |alarm| %>
        <div class="card bg-light mb-3" style="width: 20rem; float: left; margin: 10px;">
          <div class="card-header">
            <h4><%= alarm.name %></h4>
            <hr style="margin: 10px">
            <%= link_to "Upvote | #{alarm.get_upvotes.size}", upvote_alarm_path(alarm), method: :put, class: "btn btn-success btn-xs" %><span class="text-success"></span>
          </div>
        </div>
      <% end %>
</div>

<!-- Modal -->
<div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h3 class="modal-title">Create a New Alarm!</h3>
      </div>
      <div class="modal-body">
        <%= form_tag( '/alarm/create', :method => :get ) do %>
          <%= label_tag "Alarm Name" %>
          <br>
          <%= text_field_tag(:name) %>
          <br>
          <br>
          <button type="submit" class="btn btn-primary">Create</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">
    <title>Bellbird</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>